### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by edward2005edward** [wkaster/N76E003#1]
sorry but this line  in MAKE file doesn't work
disasm: $(TARGET).hex
	./tools/mcs51-disasm.pl -M N76E003.h -I ./inc -fl -rj -as $(TARGET).hex > $(TARGET).a51
when I insert this line without label disasm: and tab
$(shell ./tools/mcs51-disasm.pl -M N76E003.h -I ./inc -fl -rj  $(TARGET).hex > $(TARGET).a51)
MAKE need to run twice

and how to add this command correctly
$(shell makebin -p $(TARGET).hex > $(TARGET).bin)

Thank you

**Comment by wkaster** [comment]
Please note that the disasm function need perl installed

**Comment by ATYSHAH** [comment]
Hi,
I m newbie in N76E003AT20. I need help. I did True RMS sensing of Voltages  using this IC however please guide for how to get phase sequence detection using the same sensing. 
For True RMS I took 2000 samples of each phase with level shifting method.
Using the same method and the same sensing PIN how can I get Phase sequence?
Kindly help.


Thanks You. Regards,
ATYSHAH

**Comment by ATYSHAH** [comment]
Regards,
ATYSHAH

**Comment by wkaster** [comment]
Added bin and hex output.   Removed disasm function with perl program: you can use 'make asm' now.
