### ISSUE TITLE
linux flasher

### ISSUE THREAD

**Issue by kimstik** [wkaster/N76E003#5]
Another subject if you can help:  The linux version of the flasher tool did not handle very well rewrites wen the aprom program sends to much serial data Eg: hello world source.  Windows version is fine, do you have any experience with serial communication with linux?

_Originally posted by @wkaster in https://github.com/wkaster/N76E003/issues/4#issuecomment-1064401962_

**Comment by kimstik** [comment]
lets specify exact setup.
may you show serial dump?

**Comment by wkaster** [comment]
Bug Fixed, wrong parameter value on termios sctruct.  (VTIME = 2 not 20).
